//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;

namespace ShoeboxedService.Domain.XMLResponses
{ // 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class GetBillInfoCallResponse {
    
        private GetBillInfoCallResponseBill[] itemsField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Bill", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetBillInfoCallResponseBill[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetBillInfoCallResponseBill {
    
        private GetBillInfoCallResponseBillImages[] imagesField;
    
        private string idField;
    
        private string envelopeCodeField;
    
        private string noteField;
    
        private string createDateField;
    
        private string modifyDateField;
    
        private string nameField;
    
        private string documentCurrencyField;
    
        private string accountCurrencyField;
    
        private string conversionRateField;
    
        private string documentTotalField;
    
        private string convertedTotalField;
    
        private string formattedDocumentTotalField;
    
        private string formattedConvertedTotalField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Images", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetBillInfoCallResponseBillImages[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string envelopeCode {
            get {
                return this.envelopeCodeField;
            }
            set {
                this.envelopeCodeField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string createDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string modifyDate {
            get {
                return this.modifyDateField;
            }
            set {
                this.modifyDateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string documentCurrency {
            get {
                return this.documentCurrencyField;
            }
            set {
                this.documentCurrencyField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accountCurrency {
            get {
                return this.accountCurrencyField;
            }
            set {
                this.accountCurrencyField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string conversionRate {
            get {
                return this.conversionRateField;
            }
            set {
                this.conversionRateField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string documentTotal {
            get {
                return this.documentTotalField;
            }
            set {
                this.documentTotalField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string convertedTotal {
            get {
                return this.convertedTotalField;
            }
            set {
                this.convertedTotalField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formattedDocumentTotal {
            get {
                return this.formattedDocumentTotalField;
            }
            set {
                this.formattedDocumentTotalField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string formattedConvertedTotal {
            get {
                return this.formattedConvertedTotalField;
            }
            set {
                this.formattedConvertedTotalField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetBillInfoCallResponseBillImages {
    
        private GetBillInfoCallResponseBillImagesImage[] imageField;
    
        private string countField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetBillInfoCallResponseBillImagesImage[] Image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class GetBillInfoCallResponseBillImagesImage {
    
        private string imgurlField;
    
        private string indexField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string imgurl {
            get {
                return this.imgurlField;
            }
            set {
                this.imgurlField = value;
            }
        }
    
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
    }
}